from __future__ import division
from jinja2.runtime import LoopContext, TemplateReference, Macro, Markup, TemplateRuntimeError, missing, concat, escape, markup_join, unicode_join, to_string, identity, TemplateNotFound
def run(environment):
    name = 'source/snippets/grids/ci_default.js'

    def root(context, environment=environment):
        if 0: yield None
        yield u'/* ==== Anchor Generators ==== */\nfunction createRepositoryAnchor(dataObject) { return \'/repositories/\'+dataObject.repository.key.name+\'/content\'; }\nfunction createCategoryAnchor(dataObject) { return createRepositoryAnchor(dataObject)+\'/category/\'+dataObject.category.key.name; }\nfunction createContentItemAnchor(dataObject, key) { return createRepositoryAnchor(dataObject)+\'/\'+key; }\n\n/* ==== Render Functions ==== */\nfunction renderTitleColumn(render_obj)\n{\n\tci_key = render_obj.aData[0];\n\tcontent_item = rpcTracker.dataObjects[ci_key];\n\tcell = \'<div class="gridCell ci_result"><a class="ciTitleAnchor iconButtonBox formatButton_\'+content_item.format.properties.name+\'" href="\'+createContentItemAnchor(content_item, ci_key)+\'">\'+render_obj.aData[1]+\'</a>\';\n\tcell += \'<br /><span class="parentLinks"><a href="\'+createRepositoryAnchor(content_item)+\'">\'+content_item.repository.properties.name+\'</a>\';\n\tif (content_item.category != null)\n\t{\n\t\tcell += \'&gt;<a href="\'+createCategoryAnchor(content_item)+\'">\'+content_item.category.properties.name+\'</span>\';\n\t}\n\treturn cell\n}\nfunction renderDescriptionColumn(render_obj)\n{\n\treturn \'<p class="ciDescription">\'+truncate(rpcTracker.dataObjects[render_obj.aData[0]].description, 80)+\'</p>\';\n}\nfunction getTagLink(tag)\n{\n\treturn \'<a class="tag_\'+tag.kind+\'" href="/tags/\'+tag.name+\'">\'+tag.name+\'</a>\';\n}\nfunction renderTagsColumn(render_obj)\n{\n\tvar output = [];\n\trpcTracker.dataObjects[render_obj.aData[0]].tags.forEach(function(item) {\n\t\toutput.push(getTagLink(item))\n\t});\n\treturn output.join(\', \')\n}\nfunction renderCategoryColumn(render_obj)\n{\n\tif(typeof(rpcTracker.dataObjects[render_obj.aData[0]].category) !== \'undefined\' && rpcTracker.dataObjects[render_obj.aData[0]].category !== null)\n\t{\n\t\treturn rpcTracker.dataObjects[render_obj.aData[0]].category.properties.name;\n\t}\n\telse\n\t{\n\t\treturn \'None\';\n\t}\n}\n\nciColumns = [{\'sName\':\'key\', \'bVisible\':false, \'bSortable\':false},\n\t\t\t {\'sName\':\'title\',\'sWidth\':\'35%\',\'sTitle\':\'Title\',\'fnRender\':renderTitleColumn, \'bSortable\':false},\n\t\t\t {\'sName\':\'description\',\'sWidth\':\'35%\',\'sTitle\':\'Description\', \'fnRender\':renderDescriptionColumn, \'bSortable\':false},\n\t\t\t {\'sName\':\'tags\',\'sTitle\':\'Tags\', \'sWidth\':\'30%\', \'fnRender\':renderTagsColumn, \'bSortable\':false}];'

    blocks = {}
    debug_info = ''
    return locals()